### ISSUE TITLE
Syntax error (?) prevents compiling.

### ISSUE THREAD

**Issue by Trondtr** [giellalt/keyboard-liv#1]
Error message for `make mac`

```
  KBDGEN   mac
2024-02-16T10:23:39.611798Z  INFO kbdgen: kbdgen 3.0.0-beta.5
2024-02-16T10:23:39.612410Z  INFO kbdgen::bundle: Canonical Bundle Path: "/Users/ttr000/git/giellalt/keyboard-liv/liv.kbdgen"
thread 'main' panicked at src/build/macos/macos_bundle.rs:50:59:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [mac] Error 101
```

I remove **all** lines except the ones for the mac keyboard (no longpress, no transform) but get the same message. I do not find `src/build/macos/macos_bundle.rs:50:59`.

For this repository, `./configure` (or `./autogen.sh`) did not create `build/mac`, so I did that manually, without any influence to or fro.

There seems to be a syntax error in liv.yaml, but I am not able to spot it and the error message is not to any help.

**Comment by Trondtr** [comment]
Here compiled with more error messages:

```
uit-mac-443 keyboard-liv (main)$ make mac RUST_BACKTRACE=full

*** Building keyboards for the liv language. ***

CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh '/Users/ttr000/git/giellalt/keyboard-liv/build-aux/missing' autoconf

*** macOS build! ***

  KBDGEN   mac
2024-02-16T10:38:43.494763Z  INFO kbdgen: kbdgen 3.0.0-beta.5
2024-02-16T10:38:43.494870Z  INFO kbdgen::bundle: Canonical Bundle Path: "/Users/ttr000/git/giellalt/keyboard-liv/liv.kbdgen"
thread 'main' panicked at src/build/macos/macos_bundle.rs:50:59:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:        0x100c003db - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h958f6e6821e9b0fb
   1:        0x100c280f3 - core::fmt::write::hb5e3c29742bab55e
   2:        0x100bfc52e - std::io::Write::write_fmt::h3f38404afa442946
   3:        0x100c001b9 - std::sys_common::backtrace::print::h1ce04ba6121a0174
   4:        0x100c01c35 - std::panicking::default_hook::{{closure}}::hf2e5fe71523bcace
   5:        0x100c019b4 - std::panicking::default_hook::h4f8cdc98d2dcc8c0
   6:        0x100c02093 - std::panicking::rust_panic_with_hook::h28420d44f043d3a5
   7:        0x100c01f7c - std::panicking::begin_panic_handler::{{closure}}::h6f886c0e89185cdc
   8:        0x100c008b9 - std::sys_common::backtrace::__rust_end_short_backtrace::h7ca2b2ff22d46410
   9:        0x100c01d02 - _rust_begin_unwind
  10:        0x100c6dc15 - core::panicking::panic_fmt::h52dad7a658d9bf41
  11:        0x100c6dca7 - core::panicking::panic::ha1c871ecc7d4b1cb
  12:        0x100533f79 - kbdgen::build::macos::macos_bundle::MacOsBundle::new::h528e5b434d40666e
  13:        0x10043c9b7 - <kbdgen::build::macos::generate_macos::GenerateMacOs as kbdgen::build::BuildStep>::build::{{closure}}::hf2bf833ba0a29713
  14:        0x1003a4f45 - kbdgen::build::BuildSteps::build_full::{{closure}}::ha35a49eac906b975
  15:        0x1003889c3 - kbdgen::main::{{closure}}::hf1eac18540aa23c2
  16:        0x10038750a - tokio::runtime::park::CachedParkThread::block_on::h4ce74b01506a3236
  17:        0x1003bbb35 - tokio::runtime::context::runtime::enter_runtime::h33a06c7d15b341bb
  18:        0x1003cfca0 - tokio::runtime::runtime::Runtime::block_on::h562b406fbc875cec
  19:        0x1003b74b7 - kbdgen::main::hea2319d0dace573b
  20:        0x1003bc586 - std::sys_common::backtrace::__rust_begin_short_backtrace::h49a9707a3698f8a1
  21:        0x1003afa91 - std::rt::lang_start::{{closure}}::h7b5a91357df57f11
  22:        0x100bf5486 - std::rt::lang_start_internal::h13f88294184c535a
  23:        0x1003afa75 - std::rt::lang_start::hc1d5e0e0c08d382f
  24:     0x7ff80081c386 - <unknown>
make: *** [mac] Error 101
```

**Comment by snomos** [comment]
With the latest [kbdgen](https://github.com/divvun/kbdgen/), `make mac` works for me:

```
*** Building keyboards for the liv language. ***

CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh '/Users/smo036/langtech/gut/giellalt/keyboard-liv/build-aux/missing' autoconf

*** macOS build! ***

  KBDGEN   mac
2025-08-07T06:06:18.134562Z  INFO kbdgen: kbdgen 3.0.0-beta.5
2025-08-07T06:06:18.134888Z  INFO kbdgen::bundle: Canonical Bundle Path: "/Users/smo036/langtech/gut/giellalt/keyboard-liv/liv.kbdgen"
2025-08-07T06:06:18.876070Z  INFO kbdgen::build::macos::package_macos: Creating installer at "/Users/smo036/langtech/gut/giellalt/keyboard-liv/build/mac"...
pkgbuild: Adding component at /Users/smo036/langtech/gut/giellalt/keyboard-liv/build/mac/no.uit.giella.keyboards.liv.keyboardlayout.liv.bundle
pkgbuild: Wrote package to /var/folders/0h/1qc7g79j7tn1cvglh9r4z98w0000gp/T/.tmpgNGRm2/inner.pkg
2025-08-07T06:06:19.097381Z  INFO kbdgen::build::macos::package_macos: Running 'productbuild'...
productbuild: Wrote product to /Users/smo036/langtech/gut/giellalt/keyboard-liv/build/mac/no.uit.giella.keyboards.liv.keyboardlayout.liv.pkg
```

Closing.
